OTD/urls.py
from django.conf.urls import patterns, include, url

from django.contrib.auth.views import login, logout
from django.contrib import admin

from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'people.views.home', name='home'),

    url(r'', include('social_auth.urls')),

    url(r'^people/', include('people.urls')),
    #url(r'^pagseguro/', include('pagseguro.urls')),
    #url(r'^feedback/', include('djangovoice.urls')),
    url(r'^comments/', include('django.contrib.comments.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', logout, {"next_page": "/"}, name='logout'),
    url(r'^register/$', 'people.views.user_register', name='user_register'),
    #url(r'^base.html/$', 'django.views.generic.simple.direct_to_template', {'template': 'base.html'}),
    url(r'^base.html/$', TemplateView.as_view(template_name='base.html')),
    url(r'^login/twitter$', 'people.views.login_twitter',  name='login_twitter'),

    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),

    (r'^password_change/$', 'django.contrib.auth.views.password_change'),
    (r'^password_change/done/$', 'django.contrib.auth.views.password_change_done'),
    url(r'^password_reset/$', 'django.contrib.auth.views.password_reset', name='password_reset'),
    (r'^password_reset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^reset/done/$', 'django.contrib.auth.views.password_reset_complete'),



)

people/urls.py
from django.conf.urls import patterns, url
from django.views.generic import DetailView

from people.models import PythonGroup, UserProfile,Survey
from people.views import (
    points,
    user_profile_crud,
    python_group_crud,
    python_users_bounded,
    profile_list,
    group_list,
    survey_list,
    survey_crud,
    )

urlpatterns = patterns('',
    url(r'^kml/$', points, name='points'),
    #url(r'^profile/(?P<id>\d+)/$', user_profile_upd, name='userprofile-upd'),
    ##url(r'^profile/list/$', ListView.as_view(queryset=UserProfile.objects.order_by("name"), template_name='people/userprofile_list.html',paginate_by=15) , name="user-profile-list"),
    url(r'^profile/list/$', profile_list, name="user_profile_list"),
    url(r'^profile/(?P<pk>\d+)/$', DetailView.as_view(model=UserProfile), name="user_profile"),
    url(r'^profile/form/$', user_profile_crud, name="user_profile_form"),

    url(r'^python_group/list/$', group_list, name='python_group_list'),
    url(r'^python_group/new/$', python_group_crud, name='python_group_crud'),
    url(r'^python_group/detail/(?P<pk>\d+)/$', DetailView.as_view(model=PythonGroup), name="python_group_detail"),
    url(r'^python_group/update/(?P<pk>\d+)/$', python_group_crud, name='python_group_crud'),
    url(r'^python_group/delete/(?P<pk>\d+)/$', python_group_crud, name='python_group_crud'),

    url(r'^survey/list/$', survey_list, name='survey_list'),
    url(r'^survey/new/$', survey_crud, name='survey_new'),
    url(r'^survey/edit/(?P<pk>\d+)/$', survey_crud, name="survey_edit"),
    url(r'^survey/detail/(?P<pk>\d+)/$', DetailView.as_view(model=Survey), name="survey_detail"),

    url(r'^list/bounded/(-?\d+\.\d+)/(-?\d+\.\d+)/(-?\d+\.\d+)/(-?\d+\.\d+)/$', python_users_bounded, name="python_user_list"),
)

people/models.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.gis.db import models


SEXO_CHOICES = (
    (1, 'Male'),
    (2, 'Female'),
)


class PythonFrameWorks(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)
    site_project = models.URLField()

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']


class UserProfile(models.Model):
    """
    User Profile data
    """
    user = models.ForeignKey(User, unique=True)

    name = models.CharField(max_length=60, blank=True, null=True)
    gender = models.SmallIntegerField(choices=SEXO_CHOICES, blank=True, null=True)

    point = models.PointField(srid=settings.SRID, blank=True, null=True)
    python_frameworks = models.ManyToManyField(PythonFrameWorks, blank=True, null=True, help_text="Select one or more choices")

    #google address format
    locality = models.CharField(max_length=60, blank=True, null=True)
    administrative_area_level_1 = models.CharField(max_length=60, blank=True, null=True)
    country = models.CharField(max_length=6, blank=True, null=True)

    public_email = models.NullBooleanField('Public e-mail address ?', help_text="If 'yes', everyone may see your e-mail adress on your profile page.")

    bio = models.TextField()

    #occupation = models.ManyToManyField(Occupation)
    #organization =  models.CharField(max_length=60 , blank=True, null=True )
    #organization_site = models.URLField()
    #blog = models.URLField(verify_exists=True, blank=True, null=True )
    #site = models.URLField(verify_exists=True, blank=True, null=True )
    #twitter = models.CharField(blank=True, null=True )
    #bio  = models.TextField( blank=True, null=True , blank=True, null=True )
    objects = models.GeoManager()

    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('user_profile', args=[self.id])


class PythonGroup(models.Model):

    name = models.CharField(max_length=60, blank=False, null=False)
    description = models.TextField(blank=True, null=True)
    site_url = models.URLField(blank=True, null=True)
    contact = models.EmailField(blank=False, null=False)
    mailing_list_url = models.URLField(blank=True, null=True)

    point = models.PointField(srid=settings.SRID, blank=False, null=False)
    #google address format
    locality = models.CharField(max_length=60, blank=True, null=True)
    administrative_area_level_1 = models.CharField(max_length=60, blank=True, null=True)
    country = models.CharField(max_length=6, blank=False, null=False)

    date_add = models.DateField(auto_now_add=True)
    date_upd = models.DateField(auto_now=True)
    user = models.ForeignKey(User)

    objects = models.GeoManager()

    def __unicode__(self):
        return self.name

    def is_group_owner(self, user):
        '''return true if user is the owner or if it has no owner.'''
        return (self.user == user) or not self.user


class Survey(models.Model):
    choices_degree = (
        (1, "newbie"), (2, "novice"), (3, "apprentice"),  (4, "expert"), (5, "master")
        )

    choices_user_type = (
        (1, 'student'), (2, 'work as a developer'), (3, u'scientist / researcher'), (4, 'Other - (ex: geographer, lawyer ...)')
        )

    choices_main_context = (
        (1, "commercial"), (2, "academic / scientific research"), (3, "gov"), (4, "ngos"), (5, "help open source projects")
        )

    choices_main_environment = (
        (1, "web apps"), (2, "desktop apps"), (3, "scripts (server automation, small tools, plugins ...)"))

    choices_main_problem = (
        (1, u"as a glue language (ex: exchange data between applications, services ...)"),
        (2, u"financial tools"),
        (3, u"gis tools"),
        (4, u"graphical tools"),
        (5, u"IT Infrastructure (ex.:server automation, small tools)"),
        (6, u"just have fun programming"),
        (7, u"network tools"),
        (8, u"plugin"),
        (9, u"research"),
        (10, u"testing software"),
        (11, u"web applications development  - workflow process"),
        (12, u"web CMS"),
        (13, u"other"),
        )

    user = models.ForeignKey(User)
    date_add = models.DateTimeField(u"Answers Date", auto_now_add=True)

    when_start = models.DateField(u"when do you start using python", null=True, blank=True)
    work = models.NullBooleanField(u"do you uses python at your work ?", null=True, blank=True)
    first = models.NullBooleanField(u"is python your first language ? not you like most, but you use most.", null=True, blank=True)
    degree = models.IntegerField(u"how much python do you know ? ", choices=choices_degree)
    why = models.TextField(u"Why python", null=True, blank=True)

    user_type = models.IntegerField(choices=choices_user_type, null=True, blank=True)
    user_type_description = models.CharField(u"Description", max_length=50, null=True, blank=True)

    context = models.IntegerField(u"main environment", choices=choices_main_context, null=True, blank=True)
    environment = models.IntegerField(u"main environment", choices=choices_main_environment, null=True, blank=True)

    problem = models.IntegerField(u"main problem", choices=choices_main_problem, null=True, blank=True)
    problem_description = models.CharField(u"Description", max_length=50, null=True, blank=True)

    def __unicode__(self):
        return str(self.date_add)

    def is_survey_owner(self, user):
        '''return true if user is the owner or if it has no owner.
            to implement per user object check
        '''
        return (self.user == user) or not self.user

people/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse
from django.conf import settings

from django.utils.decorators import method_decorator
import simplejson  as json

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.gis.shortcuts import render_to_kml
from django.contrib.gis.db.models import *
from django.contrib.gis.geos import Polygon
from django.contrib import messages

from django.shortcuts import render, redirect, HttpResponse

from django.views.generic import ListView, CreateView, UpdateView

from people.forms import UserProfileForm, ProfileSearchForm, UserRegisterForm, PythonGroupForm, GroupSearchForm, SurveySearchForm, SurveyForm
from people.models import UserProfile, PythonFrameWorks, PythonGroup, Survey


def gender_count():
    profiles = list(UserProfile.objects.values('gender').annotate(Count('gender')))
    l = list()
    opts = {1: 'male', 2: 'female', 3: 'other'}
    for i in profiles:
        if (i['gender__count'] != None) and (i['gender'] != None):
            l.append([opts.get(i['gender']), i['gender__count']])
    return (l)


def frameworks_count():
    q = list(PythonFrameWorks.objects.values().annotate(Count('userprofile')))
    l = list()
    l = [[i['name'], i['userprofile__count']] for i in q]
    return (l)


def people_by_country():
    by_country = UserProfile.objects.values('country').annotate(qtd=Count('id')).order_by('-qtd')[:10]
    l = [[i['country'], i['qtd']] for i in by_country]
    return (l)


def points(request):
    points = UserProfile.objects.kml()
    return render_to_kml("placemarks.kml", {'points': points})


def home(request):
    pus = UserProfile.objects.filter(~Q(point=None))
    pygs = PythonGroup.objects.filter(~Q(point=None))
    pygs = pygs.order_by('-date_add')[:10]
    users = User.objects.all().order_by('-date_joined')[:10]
    #str_json = ups.geojson().values('user_id','name', 'gender','point')
    dpyu = [{'user_id':pu.id, 'name':pu.name, 'gender':pu.gender, 'x':pu.point.x, 'y': pu.point.y} for pu in pus]
    dpygs = [{'pyg_id':pyg.id, 'name':pyg.name, 'description':pyg.description, 'x':pyg.point.x, 'y': pyg.point.y} for pyg in pygs]

    return render(request, 'home.html', {
        'pjson': json.dumps(dpyu),
        'pygsjson': json.dumps(dpygs),
        'users': users,
        'pygs': pygs[:10],
        'gender_count': gender_count(),
        'frameworks_count': json.dumps(frameworks_count()),
        'by_country': json.dumps(list(people_by_country())),
        'people_total': User.objects.count(),
        })


def login_twitter(request):
    '''
    callback view from twitter
    '''
    return redirect(reverse('user_profile_form'))


class CreateWMsgView(CreateView):
    message = u''
    message_level = messages.INFO

    def form_valid(self, form):
        messages.add_message(self.request, self.message_level, self.message)
        return super(CreateWMsgView, self).form_valid(form)


def user_register(request, pk=None):
    view_kwargs = {
        'model': User,
        'form_class': UserRegisterForm,
        'template_name': "people/register_form.html",
        'message': u'Your account has been created ! Sig in to fullfill your profile.',
        'message_level': messages.INFO,
    }

    if pk is None:
        view_kwargs['success_url'] = "/login/"
        return CreateWMsgView.as_view(**view_kwargs)(request)
    else:
        return UpdateView.as_view(**view_kwargs)(request, pk=pk)


def user_profile_crud(request):
    python_groups = None
    if request.user.is_authenticated():

        profile, created = UserProfile.objects.get_or_create(user=request.user)
        profile.name = profile.name or request.user.first_name

        form = UserProfileForm(request.POST or None, instance=profile)

        python_groups = profile.user.pythongroup_set.all()

        if request.POST:
            if form.is_valid():
                form.save()
    else:
        form = None
        messages.add_message(request, messages.INFO, 'You may sign in to update your profile.')
    return render(request,
        "people/userprofile_form.html",
        {'form': form,
        'python_groups': python_groups},
        )


def python_group_crud(request, pk=None):

    try:
        group = PythonGroup.objects.get(pk=pk)
        if not group.is_group_owner(request.user):
            group = None
            messages.add_message(request, messages.INFO, 'You cannot update this python user group.')
            return redirect(reverse('python_group_list'))
    except:
        group = None

    form = PythonGroupForm(request.POST or None, instance=group, user=request.user)

    if request.POST:
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'The group data was sucessfully updated')
            if group==None and pk==None:
                group = PythonGroup.objects.filter(user=request.user).latest('date_add')
            return redirect(reverse('python_group_detail', args=[group.pk]))
        else:
            messages.add_message(request, messages.ERROR, 'There are erros in your request. Please check the messages below.')
    return render(request,
        "people/pythongroup_form.html",
        {'form': form},
        )


def python_users_bounded(request, *args):

    pyus = UserProfile.objects.filter(point__contained=Polygon.from_bbox(args)).order_by('name')
    pyus.filter(~Q(point=None))

    dpyu = [{'name': pyu.name, 'gender': pyu.gender, 'x': pyu.point.x, 'y': pyu.point.y, 'user_id':pyu.user_id} for pyu in pyus]
    return HttpResponse(json.dumps(dpyu), 'json')


class SearchListView(ListView):
    form_class = None

    def get_context_data(self, **kwargs):
        context = super(SearchListView, self).get_context_data(**kwargs)
        context['frm_srch'] = self.get_form()
        qs_data = context['frm_srch'].data
        context['query_string'] = ''
        if qs_data:
            qs_data.pop('page', '1')
            context['query_string'] = qs_data.urlencode()

        return context

    def get_queryset(self):
        if self.form_class is None:
            return super(SearchListView, self).get_queryset()
        return self.get_form().get_queryset()

    def get_form(self):
        #if not hasattr(self, '_inst_form'):
        #   setattr(self, '_inst_form', self.form_class(self.request.GET.copy() or None))
        #return self._inst_form
        return self.form_class(self.request.GET.copy() or None)


class ProfileListView(SearchListView):
    form_class = ProfileSearchForm
    paginate_by = 20

profile_list = ProfileListView.as_view()


class GroupListView(SearchListView):
    form_class = GroupSearchForm
    paginate_by = 20

group_list = GroupListView.as_view()


def survey_crud(request, pk=None):

    try:
        survey = Survey.objects.get(pk=pk)
        if not survey.is_group_owner(request.user):
            survey = None
            messages.add_message(request, messages.INFO, 'You cannot update this python user group.')
            return redirect(reverse('survey_list'))
    except:
        survey = None

    form = SurveyForm(request.POST or None, instance=survey, user=request.user)

    if request.POST:
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.INFO, 'The survey was sucessfully updated')
            if survey==None and pk==None:
                survey = Survey.objects.filter(user=request.user).latest('date_add')
            return redirect(reverse('survey_detail', args=[survey.pk]))
        else:
            messages.add_message(request, messages.ERROR, 'There are erros in your request. Please check the messages below.')
    return render(request,
        "people/survey_form.html",
        {'form': form},
        )


class SurveyListView(SearchListView):
    form_class = SurveySearchForm
    paginate_by = 20

survey_list = SurveyListView.as_view()

people/templates/people/pythongroup_detail.html
{% extends "base.html" %}
{% block js %} 
{{ form.media }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.6.4.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/map_functions.min.js"></script> 
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
<script type="text/javascript"> 
var geocoder;
var map;
var marker=null;
function init_mapa() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng({{object.point.get_x}}, {{object.point.get_y}});
    var myOptions = {zoom: 4, center: latlng, mapTypeId: google.maps.MapTypeId.ROADMAP }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    marker = new google.maps.Marker({ map: map,position: map.getCenter(), draggable:true});
    marker.setPosition(latlng);
    setZoomToLatLng(map, latlng,6);
};
                                  
jQuery(document).ready(function(){
    init_mapa();
    });
</script> 
{% endblock %}
{% block pagetitle %}{% firstof object.name "--" %} {% endblock %}
{% block content %}
<div class="row">
<div class="span5">
      <dl>
        <dt>about </dt>
        <dd>{% firstof object.description "--" %}</dd>
        <dt>site</dt>
        {% if  object.site_url %}
        <dd> <a href="{{ object.site_url }}">{{ object.site_url }}</a> </dd>
        {% else %}
        <dd>No site url founded</dd>
        {%  endif%}
        <dt>Contact </dt>
        <dd> {{ object.contact }} </dd>
        <dt>Group added by:<a href="{{ object.user.get_profile.get_absolute_url }}"> {% firstof object.user.get_profile.name "--" %} </a></dt>
      </dl>
    </div>
<div class="span5">
<div id="map_canvas" style="float:left;width:400px;height:350px;border:5px solid #ccc;margin:auto;top:20px;"></div>
</div>
</div>
 
{% endblock %}

people/templates/people/pythongroup_form.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block js %} 
{{ form.media }}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery-1.6.4.min.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/map_functions.min.js"></script> 
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
<script type="text/javascript"> 
var geocoder;
var map;
var marker=null;
function init_mapa() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng(-20, -48);
    var myOptions = {zoom: 4, center: latlng, mapTypeId: google.maps.MapTypeId.ROADMAP }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    marker = new google.maps.Marker({ map: map,position: map.getCenter(), draggable:true});
    
    if (document.getElementById("id_point").value!=''){
        latLng = wktToGoogleLanLng(document.getElementById("id_point").value);
        marker.setPosition(latLng);
        setZoomToLatLng(map, latLng, 15)
    }
    
    google.maps.event.addListener(marker, 'dragend', function(mEvent) {reverseGeo(mEvent.latLng); });
    google.maps.event.addListener(map, 'click', function(mEvent) {reverseGeo(mEvent.latLng);});

};
                                
function reverseGeo(latLng){
    marker.setPosition(latLng);
    document.getElementById("id_point").value =  "POINT (" +  latLng.lat() + " " + latLng.lng() + ")"
    var html="<ul>"
    geocoder.geocode({latLng: latLng}, function(results, status) {
        //alert(status);
        if (status == google.maps.GeocoderStatus.OK) { 
            components = results[0].address_components;
            for (var i = 0; i < components.length; i++) {
                short_name =  components[i].short_name ; 
                type =  components[i].types[0];
                long_name =  components[i].long_name;
                if (document.getElementById("id_"+type)){
                    document.getElementById("id_"+type).value = short_name;
                };
            };
        }else{
            document.getElementById('id_locality').value = '';
            document.getElementById('id_country').value = '';
            document.getElementById('id_administrative_area_level_1').value = '';
        }
    });  
 };


function codeAddress() {
    var address = document.getElementById("address").value;
    geocoder.geocode( { 'address': address}, function(results, status) {
      if (status == google.maps.GeocoderStatus.OK) {
        latLng = results[0].geometry.location;
        reverseGeo(latLng);
        setZoomToLatLng(map,latLng)
        document.getElementById("id_point").value =  "POINT (" +  latLng.lat() + " " + latLng.lng() + ")"; //wkt format
      } else {
        alert("Geocode was not successful for the following reason: " + status);
      }
    });
};
  
jQuery(document).ready(function(){
    init_mapa();
    jQuery('#id_country').width(50);
    jQuery('#id_country').attr("readonly", true); 
    jQuery('#id_administrative_area_level_1').attr("readonly", true); 
    jQuery('#id_locality').attr("readonly",true); 
    });
</script> 
{% endblock %}
{% block menu %}  

{% endblock %}

{% block content %}
<section>
  <h3>Group Python Creation Form</h3>
  <form method="post">
    {% csrf_token %}
    {% if form.has_errors %}
    {% endif %}
    <fieldset >
    <div class=" span6">
      <div class="clearfix">{% bootstrap_form form.name %}</div>
      <div class="clearfix">{% bootstrap_form form.contact %}</div>
      <div class="clearfix">{% bootstrap_form form.site_url %}</div>
      <div class="clearfix">{% bootstrap_form form.mailing_list_url %}</div>
      <div class="clearfix">{% bootstrap_form form.description %}</div>
    </div>
    <div class="span6 offset1">
      <div class="clearfix">
        
        
        <div class="input-append offset1">
          <input id="appendedInput" class="medium" type="text" size="16" name="appendedInput"><input type="button" value="Localizar" class="add-on  danger" onclick="codeAddress()"> 
        </div>
        
      
      <div class="clearfix"><div class="offset1" id="map_canvas" style="width:350px;height:250px;"></div></div>
      <div class="clearfix">{% bootstrap_form form.locality %}{{ form.point }}</div>
      <div class="clearfix">{% bootstrap_form form.administrative_area_level_1 %}</div>
      <div class="clearfix">{% bootstrap_form form.country %}</div>    
    </div>
    </div>
    <div class="actions span12">
      <button type="submit" class="btn primary"> Enviar</button>
      <button type="reset" class="btn default"> Reset</button>
    </div>
  </fieldset>
  </form>
</section>

{% endblock %}

people/templates/people/pythongroup_list.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block css %}
{% endblock %}
{% block js %}
{% endblock %}
{% block menu %}

 {% endblock %}
 {% block pagetitle %}  Python User Groups{% endblock %}{% block pagesubtitle %}&nbsp;&nbsp;<a class=" btn info " href="{% url 'python_group_crud' %}">Add a new Python User Group </a> {% endblock %}

{% block content %}
<form class="well form-search" method="GET">
{% bootstrap_form frm_srch "inline" %}
<input type="submit"  class="btn" value="Go">
</form>
<section id="python-groups">

     {% for obj in object_list %}
     <div class="user-item">
         <div class="user-name">
         	<a href="{% url 'python_group_detail' obj.id %}">  {{ obj.name|default_if_none:"- -" }}  </a>
         	<span class="discreet">Location: <b>{{ obj.administrative_area_level_1|default_if_none:" - -" }} / {{ obj.country|default_if_none:" - -" }}</b>
         		{% if user == obj.user %} <a href="{% url 'python_group_crud' obj.id %}" class=" btn "> edit group profile </a> {% endif %}
         	</span>



         </div>
     </div>

    {% endfor %}

</section>


{% endblock %}

people/templates/people/survey_detail.html
{% extends "base.html" %}
{% block pagetitle %}Survey Detail{% endblock %}
{% block content %}
<div class="row">
    <div class="span5">
      <dl>
        <dt>Date start to use python </dt>
        <dd>{% firstof object.when_start %}</dd>
        <dt>How much python do yo know</dt>
        <dd>{% firstof object.get_degree_display %}</dd>   
        <dt>Main Environment</dt>
        <dd>{% firstof object.get_context_display %}_{% firstof object.environment %}</dd>
        <dt>Main Problem</dt>
        <dd>{% firstof object.get_problem_display %}_{% firstof object.problem_description %}</dd>
        <dt>User Type</dt>
        <dd>{% firstof object.get_user_type_display %}_{% firstof object.user_type_description %}</dd>
      </dl>
    </div>
</div>
 
{% endblock %}

people/templates/people/survey_form.html
{% extends "base.html" %}
{% load bootstrap_toolkit %}
{% block content %}
<form class="vertical" method="post">
{% csrf_token %}
{{ form|as_bootstrap:"vertical" }}
<button type="submit" class="btn  btn-primary">Submit</button>
</form>
{% endblock %}

people/templates/people/userprofile_detail.html
{% extends "base.html" %}
{% load markdown_deux_tags %}
{% block js %} 

{{ form.media }}
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script> 
<script type="text/javascript"> 
var geocoder;
var map;
var marker=null;
function init_mapa() {
    geocoder = new google.maps.Geocoder();
    var latlng = new google.maps.LatLng({{object.point.get_x}}, {{object.point.get_y}});
    var myOptions = {zoom: 8, center: latlng, mapTypeId: google.maps.MapTypeId.ROADMAP }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    marker = new google.maps.Marker({ map: map,position: map.getCenter(), draggable:true});
    marker.setPosition(latlng);
    setZoomToLatLng(map, latlng,6);
};
                                  
jQuery(document).ready(function(){
    init_mapa();
    });
</script> 
{% endblock %}
{% block menu %}  

 {% endblock %}
{% block pagetitle %}User: {% firstof object.name "--" %} {% endblock %}{% block pagesubtitle %} {% endblock %}
{% block content %}
<div class="row">
  <div class="span5">
    <dl>
      {% if object.public_email %}
      <dt>E-mail address</dt>
      <dd> {% firstof object.user.email "--" %}</dd>
      {% endif  %}
      <dt>Gender</dt>
      <dd> {% firstof object.get_gender_display "--" %}</dd>
      <dt>Location</dt>
      <dd>{% firstof object.administrative_area_level_1 "--" %} -  {% firstof object.country "--" %}</dd>
      <dt>Python Frameworks </dt>
      <dd>{{ object.python_frameworks.all|join:"," }} </dd>
      <dt>Bio </dt>
      <dd>{{ object.bio|markdown}} </dd>
    </dl>
  </div>
  <div class="span5">
  <div id="map_canvas" style="width:400px;height:350px;border:5px solid #ccc;margin:auto;top:20px;"></div>
  </div>
</div>
 
{% endblock %}